package br.com.magnasistemas.planta.enumerators;

public enum Folhagem {
	SEM_FOLHA_POSSUI_FILOIDES("SEM_FOLHA_POSSUI_FILOIDES"), 
	FILOIDES_COM_CELULAR_MORTAS("FILOIDES COM CELULAR_MORTAS"), 
	FILOIDES_SEM_CELULAR_MORTAS("FILOIDES SEM CELULAR MORTAS"), 
	COMPOSTAS("COMPOSTAS"), 
	COMPOSTA_E_ESTIPULADAS("COMPOSTA E ESTIPULADAS"),
	HETERMORFICA("HETERMORFICA"), 
	SIMPLES("SIMPLES"),
	OCAS("OCAS"), 
	OPOSTAS("OPOSTAS"), 
	LISAS("LISAS"), 
	EMBRIONARIAS("EMBRIONARIAS"), 
	NERVURAS_SECUNDARIAS("NERVURAS SECUNDARIAS"),
	PARALELINERVIAS("PARALELINERVIAS"),
	PINADAS("PINADAS"), 
	OVAIS_OPOSTAS("OVAIS_OPOSTAS"), 
	CARTACEAS("CARTACEAS"), 
	TALOSAS("TALOSAS"),
	FOLHOSAS_OU_TALOSAS("FOLHOSAS OU TALOSAS"),
	NERVURAS_RETICULADAS("NERVURAS RETICULADAS"), 
	CORIACEAS("CORIACEAS"),
	ELIPTICAS("ELIPTICAS"),
	PEQUENAS_E_ESCAMIFORMES("PEQUENAS E ESCAMIFORMES"),
	FORMATO_DE_AGULHA("CORIACEAS"),
	COMPOSTA_PINADA("COMPOSTA_PINADA"),
	FLABELIFORMIS("FLABELIFORMIS"),
	ESPIRAL_OU_VERTICILIDAS("ESPIRAL OU VERTICILIDAS");

	private String tiposFolhagem;

	Folhagem(String tiposFolhagem) {
		this.tiposFolhagem = tiposFolhagem;
	}
}