package br.com.magnasistemas.planta.enumerators;

public enum Ordem {
	HEPATICAS("HEPATICAS"),
	MUSGOS("MUSGOS"),
	ANTOCEROS("ANTOCEROS"),
	LICOPODIOS("LICOPODIOS"),
	ISOETES("ISOETES"),
	SELAGINELLAS("SELAGINELLAS"),
	ROSACEAS("ROSACEAS"),
	ASTERACEAE("ASTERACEA"),
	LEGUMINOSAS("LEGUMINOSAS"),
	CYCADACEAE("CYCADACEAE"),
	ZAMIACEAE("ZAMIACEAE"),
	STANGERIACEAE("STANGERIACEAE"),
	WELWITSCHIALES("WELWITSCHIALES"),
	EPHEDRALES("EPHEDRALES"),
	GNETALES("GNETALES"),
    EQUISETOPSIDA("EQUISETOPSIDA"),
    SEM_ORDEM("SEM ORDEM"),
	POLYPODIOPSIDA_OU_MARATTIOPSIDA_OU_PSILOTOPSIDA("POLYPODIOPSIDA_OU_MARATTIOPSIDA_OU_PSILOTOPSIDA");

	
	private String tiposOrdem;

	Ordem(String tiposOrdem) {
		this.tiposOrdem = tiposOrdem;
	}


}